[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', '../../../lib', '../../..']
solc_version = '0.8.19'
fs_permissions = [
    { access = 'read', path = './test/data' },
    { access = 'read', path = './artifacts' }
]
remappings = [
    "test/=test/",
    "@openzeppelin/contracts=../../../node_modules/@openzeppelin/contracts/"
]
optimizer = false
no_match_path = "contracts/test/TestProbe.sol"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config