[profile.default]
src = 'contracts_'
out = 'artifacts'
script = 'script'
libs = [
    'lib', 
    '../../../lib',
    'node_modules',
    '../../../node_modules'
]
solc_version = '0.8.19'
remappings = [
    'test/=test/'
]

[rpc_endpoints]
sepolia =  'https://rpc-sepolia-eth.nodeguardians.io'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config