[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', '../../../lib', 'node_modules', '../../../node_modules']
solc_version = '0.8.19'
fs_permissions = [
    { access = 'read', path = './test/data' }
]
remappings = [
    'test/=test/'
]
no_match_path = "contracts/test/*.sol"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config